packages:
  - apps/*
  - packages/*

allowedBuiltDependencies: '*'

ignoreScripts: false

onlyBuiltDependencies:
  - '@strapi/strapi'
  - '@swc/core'
  - better-sqlite3
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver
